// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RlTZ6ne4PlKLgj1rqefWYPOdB1yeXgk',
    appId: '1:269664311350:web:8fdddcf6fa7179dcb76097',
    messagingSenderId: '269664311350',
    projectId: 'host-image-theraphy',
    authDomain: 'host-image-theraphy.firebaseapp.com',
    storageBucket: 'host-image-theraphy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzoGiS-0yPMFQ3u7xJyxKkEcQDE0HVuRo',
    appId: '1:269664311350:android:9e339090c742dc8db76097',
    messagingSenderId: '269664311350',
    projectId: 'host-image-theraphy',
    storageBucket: 'host-image-theraphy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2bNsfUWSrh-dghbh9kfP19l3Gni0cvg',
    appId: '1:269664311350:ios:26e661cf21be6fddb76097',
    messagingSenderId: '269664311350',
    projectId: 'host-image-theraphy',
    storageBucket: 'host-image-theraphy.appspot.com',
    iosClientId: '269664311350-v208jiu5c0ecl4hba96i31j0dnub3oke.apps.googleusercontent.com',
    iosBundleId: 'com.example.theraphyPhysiotherapistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2bNsfUWSrh-dghbh9kfP19l3Gni0cvg',
    appId: '1:269664311350:ios:ccb49f7b64174953b76097',
    messagingSenderId: '269664311350',
    projectId: 'host-image-theraphy',
    storageBucket: 'host-image-theraphy.appspot.com',
    iosClientId: '269664311350-dq6k32e8oita1i2n39gp33qpdo662vgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.theraphyPhysiotherapistApp.RunnerTests',
  );
}
